### ISSUE TITLE
Anteproyecto: ubcacion del archivo con el anteproyecto

### ISSUE THREAD

**Issue by harpomaxx** [SebaFuchi/ia-uncuyo-2021#5]
Crear en el repositorio personal de github dentro de una carpeta proyecto_final/ un archivo de nombre anteproyecto.md con toda la información mencionada con anterioridad. 

**IMPORTANTE:** en caso de ser equipos de dos, la carpeta proyecto_final/ deberá estar duplicada en ambos repositorios

**Comment by Landriou** [comment]
Ya esta resuelto todo y tambien esta la copia en mi git
